theme: jekyll-theme-minimal
title: Kaggle Airline Delay & Cancellation Analysis
description: Analyis of Domestic Airline Cancellation and Delays (2009-2018)
description_detail: Every year Domestic US Airliness report losses of $ B due to delays and cancellations. This report is an ananlyis of these delays and cancellations and the resons behind it

navigation:
  - title: Home
    url: /
  - title: Motivation
    url: motivation
  - title: About the Data
    url: about
  - title: Obtaining Data & Pre-processing
    url: obtaining
  - title: Software Requirements
    url: requirements
  - title: Data Analysis
    url: analysis
  - title: Summary
    url: summary
  - title: Glossary
    url: glossary
  - title: References
    url: references
