theme: jekyll-theme-minimal
title: Kaggle Airline Cancellation Analysis
description: description Kaggle Airline Cancellation Analysis description
var: Ayush

navigation:
  - title: Home
    url: README
  - title: Motivation
    url: README#motivation
  - title: About the Data
    url: README#about-the-data
  - title: Data Analysis
    url: README#data-analysis
  - title: Glossary
    url: README#glossary
  - title: Summary
    url: README#summary
  - title: References
    url: README#references
