theme: jekyll-theme-minimal
title: Kaggle Airline Cancellation Analysis
description: Analyis of Domestic Airline Cancellation and Delays (2009-2018)
description_detail: Every year Domestic US Airliness report losses of $ B due to delays and . This report is an ananlyis of these delays and cancellations and the resons behind it

navigation:
  - title: Home
    url: /
  - title: Motivation
    url: report
  - title: About the Data
    url: report#about-the-data
  - title: Data Analysis
    url: report#data-analysis
  - title: Glossary
    url: report#glossary
  - title: Summary
    url: report#summary
  - title: References
    url: report#references
